default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user
  password: password
  host: db

development:
  <<: *default
  database: price_alert_db

test:
  <<: *default
  database: price_alert_test_db

production:
  <<: *default
  database: price_alert_prod_db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>